// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlNDbde5jyhUIe4p8D8amaqXzkz7CB9UU',
    appId: '1:940702591840:web:0043762e200f203fc44c05',
    messagingSenderId: '940702591840',
    projectId: 'flutter-bloc-otp-auth',
    authDomain: 'flutter-bloc-otp-auth.firebaseapp.com',
    storageBucket: 'flutter-bloc-otp-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvj3klBnGSHKkzP5iVehI3SlLs69IfFM',
    appId: '1:940702591840:android:042bf1edf0040956c44c05',
    messagingSenderId: '940702591840',
    projectId: 'flutter-bloc-otp-auth',
    storageBucket: 'flutter-bloc-otp-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt_eVvzDC8cnTzd0HDInenaYLZGk2kCs8',
    appId: '1:940702591840:ios:aee48a6b48c5316ac44c05',
    messagingSenderId: '940702591840',
    projectId: 'flutter-bloc-otp-auth',
    storageBucket: 'flutter-bloc-otp-auth.appspot.com',
    iosClientId: '940702591840-h5rvi2oc3pnqu3kolqla61lnfifndrsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocOtpAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt_eVvzDC8cnTzd0HDInenaYLZGk2kCs8',
    appId: '1:940702591840:ios:50a2f55d9ee7c64ac44c05',
    messagingSenderId: '940702591840',
    projectId: 'flutter-bloc-otp-auth',
    storageBucket: 'flutter-bloc-otp-auth.appspot.com',
    iosClientId: '940702591840-n59pj1v228o7t07uift4ga77s4emg45c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBlocOtpAuthentication.RunnerTests',
  );
}
